blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls', namespace='blog_app')),
    path('users/', include('users.urls', namespace='users')),
]

blog_app/urls.py
"""Defines URL patterns for blog_app."""

from django.urls import path

from . import views

app_name = "blog_app"
urlpatterns = [
    # Home page.
    path("", views.home, name="home"),

    # Show all topics.
    path("topics/", views.topics, name="topics"),

    # Detail page for a single topic.
    path("topics/<int:topic_id>/", views.topic, name="topic"),

    # Page for adding a new topic.
    path("new_topic/", views.new_topic, name="new_topic"),

    # Page for adding a new post from the home page.
    path("new_post/", views.new_post, name="new_post"),

    # Page for adding a new post from a topic page.
    path("new_post/<int:topic_id>/", views.new_post, name="new_post"),

    # Page for editing an post.
    path("edit_post/<int:post_id>/", views.edit_post, name="edit_post"),

    # Page containing personal details
    path("about_me/", views.about_me, name="about_me"),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = "users"
urlpatterns = [
    # Login page
    path("", views.LoginView.as_view(), name="login"),

    # Logout page
    path("logout/", views.logout_view, name="logout"),
]

blog_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """The topics a post can be about""" 
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Post(models.Model):
    """Specific post about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

blog_app/forms.py
from django import forms

from .models import Topic, Post

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["topic", "text"]
        labels = {"topic":"" , "text": ""}

blog_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Post
from .forms import TopicForm, PostForm

# Create your views here.
def home(request):
    """The home page for the blog."""
    topics = Topic.objects.order_by("text")
    posts = Post.objects.order_by("date_added").reverse()
    context = {"topics": topics, "posts": posts}
    return render(request, "blog_app/home.html", context)

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by("text")
    context = {"topics": topics}
    return render(request, "blog_app/topics.html", context)

def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topics = Topic.objects.order_by("text")
    topic = Topic.objects.get(id=topic_id)
    posts = topic.post_set.order_by("date_added").reverse()
    context = {"topics": topics, "topic": topic, "posts": posts}
    return render(request, "blog_app/topic.html", context)

def about_me(request):
    """The about me page for the blog"""
    topics = Topic.objects.order_by("text")
    context = {"topics": topics}
    return render(request, "blog_app/about_me.html", context)

@login_required()
def new_topic(request):
    """Add a new topic."""
    topics = Topic.objects.order_by("text")

    if request.method != "POST":
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("blog_app:home"))

    context = {"topics": topics, "form": form}
    return render(request, "blog_app/new_topic.html", context)

@login_required
def new_post(request, topic_id=None):
    """Add a new post for a particular topic."""
    topics = Topic.objects.order_by("text")
    if topic_id:
        topic = Topic.objects.get(id=topic_id)
    else:
        topic = None

    if request.method != "POST":
        # No data submitted; create a blank form.
        form = PostForm(initial={"topic": topic})
    else:
        # POST data submitted; process data.
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save()
            if topic_id:
                return HttpResponseRedirect(reverse("blog_app:topic", args=[topic_id]))
            else:
                return HttpResponseRedirect(reverse("blog_app:home"))

    context = {"topics": topics, "topic": topic, "form": form}
    return render(request, "blog_app/new_post.html", context)

@login_required
def edit_post(request, post_id):
    """Edit an existing post."""
    topics = Topic.objects.order_by("text")
    post = Post.objects.get(id=post_id)

    if request.method != "POST":
        # Initial request; pre-fill form with the current post.
        form = PostForm(instance=post)
    else:
        # POST data is submitted; process data.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("blog_app:home"))

    context = {"topics": topics, "post": post, "form": form}
    return render(request, "blog_app/edit_post.html", context)

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import views as auth_views, logout

from blog_app.models import Topic

# Create your views here.
class LoginView(auth_views.LoginView):
    """Log the user in."""
    template_name = "users/login.html"
    topics = Topic.objects.order_by("text")
    extra_context = {"topics": topics}

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse("blog_app:home"))

blog_app/templates/blog_app/about_me.html
{% extends "blog_app/base.html" %} {% block header %}
<h2>About me</h2>
<p>
  <a href="https://github.com/Hogwarts250">Github</a> -
  <a href="https://www.instagram.com/ff.zhang/">Instagram</a> -
  <a href="mailto:felixfzhang@hotmail.com">Email</a>
</p>
{% endblock header %} {% block content %}
<p>
  I'm a grade 11 student at Saint Michael's University School hoping to study
  computer science or software engineering after I graduate. I have lived in
  Victoria, British Columbia for the almost the entirety of my life and enjoy
  the atmosphere that it has. However, one of my goals is to spend at least a
  few years of my life living in a major metropolis. Things I am likely to be
  doing in my spare time include programming / working on personal projects,
  playing Magic: the Gathering (either online or in paper at a local game
  store), or reading a book. I am currently part of the En Avant program at the
  Westcoast Academy of Performing Arts and am working towards attaining a Grade
  10 piano certificate from the Royal Conservatory of Music.
</p>
{% endblock content %}

blog_app/templates/blog_app/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Blog</title>

    {% bootstrap_css %} {% bootstrap_javascript %}
  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#navbar"
            aria-expanded="false"
            aria-controls="navbar"
          ></button>
          <a class="navbar-brand" href="{% url 'blog_app:home' %}">Home</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% for topic in topics %}
            <li><a href="{% url 'blog_app:topic' topic.id %}">{{ topic }}</a></li>
            {% endfor %}
            {% if user.is_authenticated %}
            <li><a href="{% url 'blog_app:new_topic' %}">New Topic</a></li>
            {% endif %}
            <li><a href="{% url 'blog_app:about_me' %}">About Me</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
            {% endif %}
          </ul>
        </div>
        {% if user.is_authenticated %}
        <p class="nav navbar-nav navbar-right">Hello, {{ user.first_name }}</p>
        {% endif %}
        <!-- /.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div>
    <!-- /container -->
  </body>
</html>

blog_app/templates/blog_app/edit_post.html
{% extends "blog_app/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Edit the contents of a post</h2>
{% endblock header %} {% block content %}
<form action="{% url 'blog_app:edit_post' post.id %}" method="POST" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit">Save Changes</button>
  {% endbuttons %}
</form>

{% endblock content %}

blog_app/templates/blog_app/home.html
{% extends "blog_app/base.html" %} {% block header %}
<div class="jumbotron">
  <h1>Felix's Blog</h1>
  <h3>
    A place for me to organize my thoughts and share any interesting information
    I come across.
  </h3>
</div>
{% endblock header %} {% block content %}
{% if user.is_authenticated %}
<p><a href="{% url 'blog_app:new_post' %}">new post</a></p>
{% endif %}
<ul>
  {% for post in posts %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>
        {{ post.date_added|date:"M d, Y H:i" }} - {{ post.topic }}
        {% if user.is_authenticated %}
        <small>
          <a href="{% url 'blog_app:edit_post' post.id %}">edit post</a>
        </small>
        {% endif %}
      </h3>
    </div>
    <div class="panel-body">
      {{ post.text|linebreaks }}
    </div>
  </div> <!-- panel -->
  {% endfor %}
</ul>

{% endblock content %}

blog_app/templates/blog_app/new_post.html
{% extends "blog_app/base.html" %} {% load bootstrap3 %}

{% block header %}
<h2>Write a new post about a topic</h2>
{% endblock header %}

{% block content %}
{% if topic %}
<p><a href="{% url 'blog_app:topic' topic.id %}">Return to {{ topic }}</a></p>
{% endif %}
{% if topic %}
<form action="{% url 'blog_app:new_post' topic.id %}" method="POST" class="form">
{% else %}
<form action="{% url 'blog_app:new_post' %}" method="POST" class="form">
{% endif %}
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit">Add Post</button>
  {% endbuttons %}
</form>
{% endblock content %}

blog_app/templates/blog_app/new_topic.html
{% extends "blog_app/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Add a new topic</h2>
{% endblock header %} {% block content %}

<form action="{% url 'blog_app:new_topic' %}" method="POST" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit" class="btn btn-primary">Add Topic</button>
  {% endbuttons %}
</form>

{% endblock content %}

blog_app/templates/blog_app/topic.html
{% extends "blog_app/base.html" %} {% block header %}
<h2>{{ topic }}</h2>
{% endblock header %} {% block content %} {% if user.is_authenticated %}
<p><a href="{% url 'blog_app:new_post' topic.id %}">new post</a></p>
{% endif %}
<ul>
  {% for post in posts %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>
        {{post.date_added|date:"M d, Y H:i" }} {% if user.is_authenticated %}
        <small>
          <a href="{% url 'blog_app:edit_post' post.id %}">edit post</a>
        </small>
        {% endif %}
      </h3>
    </div>
    <div class="panel-body">
      {{ post.text|linebreaks }}
    </div>
  </div> <!-- panel -->
  {% endfor %}
</ul>

{% endblock content %}

blog_app/templates/blog_app/topics.html
{% extends "blog_app/base.html" %} {% block content %}

<p>Topics</p>
<ul>
  {% for topic in topics %}
  <li>
    <a href="{% url 'blog_app:topic' topic.id %}">{{ topic }}</a>
  </li>
  {% empty %}
  <li>No topics have been added yet.</li>
  {% endfor %}
</ul>
{% endblock content %}

users/templates/users/login.html
{% extends "blog_app/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Login to your account</h2>
{% endblock header %} {% block content %}

<form method="POST" action="{% url 'users:login' %}" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit" class="btn btn-primary">Login</button>
  {% endbuttons %}

  <input type="hidden" name="next" value="{% url 'blog_app:home' %}" />
</form>
{% endblock content %}